export let projects =[
    {src:"https://ellinsa.github.io/blog-application-template/",
     github:"https://github.com/Ellinsa/blog-application-template",
     name:"Blog application",
     description:"A simple blog app with pagination and form (React,SCSS,TypeScript)",
     img:"/blogwebsite.png"},
    {src:"https://ellinsa.github.io/montageWEB/",
     github:"https://github.com/Ellinsa/montageWEB",
     name:"Montage Landing page",
     description:"A landing page for the local russian company",
     img:"/montagewebsite.png"},
    {src:"https://toriatova.web.app/",
     github:"https://github.com/Ellinsa/ToriTovaWebDev",
     name:"My portfolio",
     description:"My portfolio website (Svelte, Firebase)",
     img:"/myportfolio.png"},
    {src:"",
     github:"",
     name:"",
     description:"",
     img:""},
    {src:"",
     github:"",
     name:"",
     description:"",
     img:""},
    {src:"",
     github:"",
     name:"",
     description:"",
     img:""},
    {src:"",
     github:"",
     name:"",
     description:"",
     img:""},
    {src:"",
     github:"",
     name:"",
     description:"",
     img:""},
]